services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # apps
      - "15672:15672"     # ui
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest